name: hsf-india
channels:
  - conda-forge
dependencies:
  - python==3.13
  - pip
  - cmake 
  - openssh 
  - jupyter-server-proxy
  - python-build
  - code-server >=3.2
  - pip:
      - jupyterlab-deck
      - jupyterlab-mathjax3
      - matplotlib     
      - numpy
      - requests
      - uproot
      - fsspec-xrootd
      - xrootd
      - particle
      - scipy
      - pandas
      - vector
      - bash_kernel
#      - jupyter-vscode-server
  
     
variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
