name: hsf-india
channels:
  - conda-forge
dependencies:
  - python==3.12
  - pip
  - cmake 
  - openssh 
  - singularity
  - ncurses
  - vim
  - emacs
  - nano
  - ipykernel
  - libuuid
  - pip:
      - jupyterlab-deck
      - jupyterlab-mathjax3
      - matplotlib     
      - numpy
      - requests
      - uproot
      - fsspec-xrootd
      - xrootd
      - particle
      - scipy
      - pandas
      - vector
      - bash_kernel
     
variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
