name: hsf-india-python
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab-book
  - jupyterlab
  - jupytext
  - nbconvert
  - jupyterlab-mathjax3
  - vim
  - juliaup
  - pyjuliacall
- pip:
  - jupyterlab-rise
