#!/bin/bash


git clone https://github.com/peremato/Geant4.jl-tutorial
git clone https://github.com/JuliaHEP/Hands-on-Julia-for-particle-physicists

cd Hands-on-Julia-for-particle-physicists/julia-intro 
jupyter-book build ./docs > log.book
cd ../..
exec "$@"
